name: FidyDdns
services:
  client:
    container_name: client
    restart: on-failure
    volumes:
      - ./config.json:/config.json
      - ./myIp.sh:/myIp.sh:ro
    image: dockerhub.qingcloud.com/fidy_tools/ddns
